#ifndef PackageRoot
  #error PackageRoot is required
#endif
#ifndef OutputDirectory
  #error OutputDirectory is required
#endif
#ifndef AppVersion
  #error AppVersion is required
#endif
#ifndef DesktopUrl
  #error DesktopUrl is required
#endif
#ifndef DesktopSha256
  #error DesktopSha256 is required
#endif
#ifndef DesktopSize
  #error DesktopSize is required
#endif
#ifndef DesktopVersion
  #error DesktopVersion is required
#endif
#ifndef DesktopPublisher
  #error DesktopPublisher is required
#endif
#if Ver < EncodeVer(6, 5, 0)
  #error Inno Setup 6.5 or later is required
#endif

[Setup]
AppId={{DA05A763-8CD9-4718-B131-9CDB23C52BC8}
AppName=CodexZero
AppVersion={#AppVersion}
AppPublisher=CodexZero
DefaultDirName={localappdata}\Programs\CodexZero
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableDirPage=yes
DisableProgramGroupPage=yes
DisableWelcomePage=yes
UninstallDisplayName=CodexZero
UninstallDisplayIcon={app}\assets\codexzero.ico
SetupIconFile={#PackageRoot}\assets\codexzero.ico
OutputDir={#OutputDirectory}
OutputBaseFilename=CodexZero-Setup-windows-x64
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
CloseApplications=no
RestartApplications=no
Uninstallable=yes

[Files]
; The desktop application is assembled on this computer from the official package.
Source: "{#PackageRoot}\*"; DestDir: "{tmp}\package"; Flags: ignoreversion recursesubdirs createallsubdirs deleteafterinstall
Source: "{#DesktopUrl}"; DestDir: "{tmp}"; DestName: "codex-desktop.msix"; Hash: "{#DesktopSha256}"; ExternalSize: {#DesktopSize}; Flags: external download ignoreversion deleteafterinstall; Check: NeedsDesktopDownload
Source: "{#PackageRoot}\assets\codexzero.ico"; DestDir: "{app}\assets"; Flags: ignoreversion

[Icons]
Name: "{userprograms}\CodexZero"; Filename: "{app}\CodexZero.exe"; WorkingDir: "{app}"; IconFilename: "{app}\assets\codexzero.ico"
Name: "{userdesktop}\CodexZero"; Filename: "{app}\CodexZero.exe"; WorkingDir: "{app}"; IconFilename: "{app}\assets\codexzero.ico"

[UninstallDelete]
; Only files generated by setup and updates. Codex chats, settings and sign-in stay.
Type: filesandordirs; Name: "{app}\updates"
Type: files; Name: "{app}\CodexZero.exe"
Type: files; Name: "{app}\current-build.txt"
Type: files; Name: "{app}\update-failed.txt"
Type: filesandordirs; Name: "{localappdata}\CodexZero\cache"

[Run]
Filename: "{app}\CodexZero.exe"; Description: "Open CodexZero"; WorkingDir: "{app}"; Flags: nowait postinstall skipifsilent; Check: CanLaunch
Filename: "{app}\CodexZero.exe"; WorkingDir: "{app}"; Flags: nowait postinstall skipifnotsilent; Check: CanLaunchSilently

[Code]
const
  InstalledDesktopKey = 'Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\OpenAI.Codex_{#DesktopVersion}_x64__{#DesktopPublisher}';

var
  InstallReady: Boolean;
  CheckingUninstall: Boolean;

function GetCurrentProcessId(): Cardinal;
  external 'GetCurrentProcessId@kernel32.dll stdcall';

// Match the installation path, never a process name shared with original Codex.
function InstallationIsRunning(): Boolean;
var
  Locator, Services, Processes, Process: Variant;
  Index: Integer;
  CurrentPid, UninstallerParentPid: Cardinal;
  Root, Executable, CommandLine: String;
begin
  if not FileExists(ExpandConstant('{app}\CodexZero.exe')) and
     not FileExists(ExpandConstant('{app}\desktop\ChatGPT.exe')) then begin
    Result := False;
    Exit;
  end;
  Result := True;
  Root := Lowercase(AddBackslash(ExpandConstant('{app}')));
  try
    Locator := CreateOleObject('WbemScripting.SWbemLocator');
    Services := Locator.ConnectServer('', 'root\CIMV2');
    CurrentPid := GetCurrentProcessId();
    UninstallerParentPid := 0;
    Processes := Services.ExecQuery('SELECT ProcessId, ParentProcessId, ExecutablePath, CommandLine FROM Win32_Process');
    // Uninstall executes from a temporary copy while its original parent waits.
    if CheckingUninstall then
      for Index := 0 to Processes.Count - 1 do begin
        Process := Processes.ItemIndex(Index);
        if Process.ProcessId = CurrentPid then
          UninstallerParentPid := Process.ParentProcessId;
      end;
    for Index := 0 to Processes.Count - 1 do begin
      Process := Processes.ItemIndex(Index);
      if Process.ProcessId = CurrentPid then Continue;
      if not VarIsNull(Process.ExecutablePath) then begin
        // WMI values are variants. Assign before calling string functions.
        Executable := Process.ExecutablePath;
        Executable := Lowercase(Executable);
        if CheckingUninstall and (Process.ProcessId = UninstallerParentPid) then
          if CompareText(Executable, ExpandConstant('{uninstallexe}')) = 0 then Continue;
        if Pos(Root, Executable) = 1 then Exit;
      end;
      // The update helper runs in PowerShell outside the installation tree.
      if not VarIsNull(Process.CommandLine) then begin
        CommandLine := Process.CommandLine;
        CommandLine := Lowercase(CommandLine);
        if ((Pos('complete-desktop-update.ps1', CommandLine) > 0) or
            ((Pos('updates\.stage-', CommandLine) > 0) and
             (Pos('\complete.ps1', CommandLine) > 0))) and
           (Pos(Root, CommandLine) > 0) then Exit;
      end;
    end;
    Result := False;
  except
    // Do not replace a live installation when its process state is unknown.
    Log('Could not inspect running processes.');
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  if InstallationIsRunning() then
    Result := 'Close CodexZero before continuing.';
end;

// Skip the download when the matching app or an earlier download is available.
function NeedsDesktopDownload(): Boolean;
begin
  Result := not RegKeyExists(HKCU, InstalledDesktopKey) and
    not FileExists(ExpandConstant('{localappdata}\CodexZero\cache\desktop\{#DesktopVersion}.msix'));
end;

procedure AssembleDesktop();
var
  Package, DesktopPackage, Params: String;
  ResultCode: Integer;
  Started: Boolean;
begin
  Package := ExpandConstant('{tmp}\package');
  DesktopPackage := ExpandConstant('{tmp}\codex-desktop.msix');
  Params := '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "' + Package + '\scripts\install-desktop.ps1"' +
    ' -PackageRoot "' + Package + '" -InstallRoot "' + ExpandConstant('{app}') + '" -Installer setup -NoLaunch -SkipShortcuts';
  if FileExists(DesktopPackage) then
    Params := Params + ' -DesktopPackage "' + DesktopPackage + '"';
  WizardForm.StatusLabel.Caption := 'Setting up CodexZero...';
  WizardForm.FilenameLabel.Caption := '';
  WizardForm.ProgressGauge.Style := npbstMarquee;
  try
    Started := ExecAndLogOutput(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'), Params, '',
      SW_HIDE, ewWaitUntilTerminated, ResultCode, nil);
  finally
    WizardForm.ProgressGauge.Style := npbstNormal;
  end;
  if not Started or (ResultCode <> 0) then
    RaiseException('CodexZero could not finish setting up. Check your internet connection, then run setup again.');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then begin
    // The launcher switches to the new build only after it is complete.
    AssembleDesktop();
    InstallReady := FileExists(ExpandConstant('{app}\CodexZero.exe')) and
      FileExists(ExpandConstant('{app}\current-build.txt'));
    if not InstallReady then
      RaiseException('Could not finish installing CodexZero. Close CodexZero and run setup again.');
  end;
end;

function CanLaunch(): Boolean;
var
  Index: Integer;
begin
  Result := InstallReady;
  for Index := 1 to ParamCount do
    if CompareText(ParamStr(Index), '/NOLAUNCH') = 0 then
      Result := False;
end;

function CanLaunchSilently(): Boolean;
begin
  Result := WizardSilent and CanLaunch();
end;

function InitializeUninstall(): Boolean;
begin
  CheckingUninstall := True;
  Result := not InstallationIsRunning();
  if not Result then
    MsgBox('Close CodexZero before continuing.', mbError, MB_OK);
end;
